name: system information actions
on: 
 push:
   branches: [ main ]
jobs:
  sysinfo-workflow-actions:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        node-version: [18.12.1]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run test
